### ISSUE TITLE
Accordion Widget: Element not clickable at point.  Works on home laptop but not work laptop

### ISSUE THREAD

**Issue by Murp01** [Murp01/Java-Cucumber_Company-Website#6]
When running accordion feature test it fails on step where it opens all closed tabs.  This worked fine at home but when executing on work laptop the following error is shown in console.  Note, the first tab will be opened, it's the second which fails.

Feature: Accordion Widget
  
  The website uses an accordion widget to neatly show subject headers with its content hidden until clicked.
  Upon clicking on the subject header the content will be displayed below.  The content can contain links which
  when clicked on will redirect to another webpage.  Each segment will remain open when another has been clicked
  on.  When arriving on a webage that contains an accordion feature all segments will be closed by default
Starting ChromeDriver 2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387) on port 43156
Only local connections are allowed.
Jan 18, 2019 3:20:38 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

  @Testme
  Scenario: Open all accordions segments                            # src/test/java/resources/features/AccordionWidget.feature:9
    Given I am on the "https://www.linklaters.com/en/about-us" page # CareersPage_Steps.i_am_on_the_page(String)
    When I click on each "closed" accordions segments               # AboutUsSteps.i_click_on_each_accordions_segments(String)
      org.openqa.selenium.WebDriverException: unknown error: Element <h2 data-open="False" class="ui-accordion-header ui-corner-top ui-accordion-header-collapsed ui-corner-all ui-state-default ui-accordion-icons" role="tab" id="ui-id-3" aria-controls="ui-id-4" aria-selected="false" aria-expanded="false" tabindex="-1">...</h2> is not clickable at point (431, 584). Other element would receive the click: <p>...</p>
        (Session info: chrome=71.0.3578.98)
        (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17763 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 0 milliseconds
      Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
      System info: host: 'ROQ-028', ip: '192.168.1.36', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
      Driver info: org.openqa.selenium.chrome.ChromeDriver
      Capabilities [{mobileEmulationEnabled=false, timeouts={implicit=0, pageLoad=300000, script=30000}, hasTouchScreen=false, platform=XP, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:56261}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, platformName=XP, setWindowRect=true, unexpectedAlertBehaviour=ignore, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387), userDataDir=C:\Users\PAUL~1.MUR\AppData\Local\Temp\scoped_dir16980_22027}, takesHeapSnapshot=true, unhandledPromptBehavior=ignore, pageLoadStrategy=normal, strictFileInteractability=false, databaseEnabled=false, handlesAlerts=true, version=71.0.3578.98, browserConnectionEnabled=false, proxy=Proxy(), nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
      Session ID: daa96898224df24cf939b8add962302c
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
      	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
      	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
      	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
      	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
      	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
      	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
      	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
      	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
      	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      	at java.lang.reflect.Method.invoke(Method.java:498)
      	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
      	at com.sun.proxy.$Proxy22.click(Unknown Source)
      	at pageObjects.AboutUs_Page.clickOnClosedAccordionTabs(AboutUs_Page.java:48)
      	at stepDefinitions.AboutUsSteps.i_click_on_each_accordions_segments(AboutUsSteps.java:31)
      	at ✽.When I click on each "closed" accordions segments(src/test/java/resources/features/AccordionWidget.feature:11)

    Then the correct content will be displayed                      # AboutUsSteps.the_correct_content_will_be_displayed()

Failed scenarios:
src/test/java/resources/features/AccordionWidget.feature:9 # Scenario: Open all accordions segments

1 Scenarios (1 failed)
3 Steps (1 failed, 1 skipped, 1 passed)
0m16.847s

org.openqa.selenium.WebDriverException: unknown error: Element <h2 data-open="False" class="ui-accordion-header ui-corner-top ui-accordion-header-collapsed ui-corner-all ui-state-default ui-accordion-icons" role="tab" id="ui-id-3" aria-controls="ui-id-4" aria-selected="false" aria-expanded="false" tabindex="-1">...</h2> is not clickable at point (431, 584). Other element would receive the click: <p>...</p>
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17763 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'ROQ-028', ip: '192.168.1.36', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_171'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{mobileEmulationEnabled=false, timeouts={implicit=0, pageLoad=300000, script=30000}, hasTouchScreen=false, platform=XP, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:56261}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, platformName=XP, setWindowRect=true, unexpectedAlertBehaviour=ignore, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387), userDataDir=C:\Users\PAUL~1.MUR\AppData\Local\Temp\scoped_dir16980_22027}, takesHeapSnapshot=true, unhandledPromptBehavior=ignore, pageLoadStrategy=normal, strictFileInteractability=false, databaseEnabled=false, handlesAlerts=true, version=71.0.3578.98, browserConnectionEnabled=false, proxy=Proxy(), nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: daa96898224df24cf939b8add962302c
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy22.click(Unknown Source)
	at pageObjects.AboutUs_Page.clickOnClosedAccordionTabs(AboutUs_Page.java:48)
	at stepDefinitions.AboutUsSteps.i_click_on_each_accordions_segments(AboutUsSteps.java:31)
	at ✽.When I click on each "closed" accordions segments(src/test/java/resources/features/AccordionWidget.feature:11)

**Comment by Murp01** [comment]
Worked a treat

![image](https://user-images.githubusercontent.com/22293195/51396054-2d144d80-1b36-11e9-8a2e-ccc8fdbf8e96.png)
